version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  db:
    image: bitnami/mariadb:latest
    container_name: taskscheduler-db
    restart: always
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    networks:
      - app-tier
    ports:
      - "3307:3306"
    volumes:
      - my_taskscheduler_db_data:/bitnami/mariadb
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql 
  
  app:
    build: .
    image: taskscheduler-app
    container_name: taskscheduler-app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mariadb://${MARIADB_USER}:${MARIADB_PASSWORD}@db:3306/${MARIADB_DATABASE}
    networks: 
      - app-tier

volumes:
  my_taskscheduler_db_data:
