# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-service
# spec:
#   ports:
#   - port: 3306
#     targetPort: 3306
#   selector:
#     app: mariadb
# ---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-table-job
spec:
  template:
    spec:
      containers:
      - name: create-table
        image: bitnami/mariadb:latest
        command: ["/bin/sh", "-c", "mariadb -h mysql-service -u$MARIADB_USER -p$MARIADB_PASSWORD $MARIADB_DATABASE -e 'CREATE TABLE IF NOT EXISTS tasks (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL UNIQUE, scheduled_time DATETIME NOT NULL, recurrence ENUM(\"ONCE\", \"DAILY\", \"WEEKLY\", \"BIWEEKLY\", \"MONTHLY\", \"QUARTERLY\", \"YEARLY\") NULL);'"]
        env:
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: read-tasks-job
spec:
  template:
    spec:
      containers:
      - name: read-tasks
        image: bitnami/mariadb:latest
        command: ["/bin/sh", "-c", "mariadb -h mysql-service -u$MARIADB_USER -p$MARIADB_PASSWORD $MARIADB_DATABASE -e 'SELECT * FROM tasks;'"]
        env:
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: update-task-job
spec:
  template:
    spec:
      containers:
      - name: update-task
        image: bitnami/mariadb:latest
        command: ["/bin/sh", "-c", "mariadb -h mysql-service -u$MARIADB_USER -p$MARIADB_PASSWORD $MARIADB_DATABASE -e 'UPDATE tasks SET recurrence = \"DAILY\" WHERE id = 1;'"]
        env:
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-task-job
spec:
  template:
    spec:
      containers:
      - name: delete-task
        image: bitnami/mariadb:latest
        command: ["/bin/sh", "-c", "mariadb -h mysql-service -u$MARIADB_USER -p$MARIADB_PASSWORD $MARIADB_DATABASE -e 'DELETE FROM tasks WHERE id = 1;'"]
        env:
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database
      restartPolicy: Never
