apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
  database: dGFza3NjaGVkdWxlcg==
  mariadb-root-password: YWRtaW4=
  mariadb-user: YWRtaW4=
  mariadb-password: dGFza3NjaGVkdWxlcg==
