apiVersion: batch/v1
kind: CronJob
metadata:
  name: weekly-grocery-shopping-1000
  labels:
    id: job-1
spec:
  schedule: "*/5 * * * *" 
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: task-scheduler-job
        spec:
          containers:
          - name: curl-container
            image: curlimages/curl:7.78.0
            command: ["sh", "-c"]
            args:
            - |
                curl -X 'POST' \
                  'http://task-scheduler-service:8000/api/tasks/' \
                  -H 'accept: application/json' \
                  -H 'Content-Type: application/json' \
                  -d '{
                  "name": "Weekly Grocery Shopping -- 1000",
                  "scheduled_time": "2024-03-20T10:00:00",
                  "recurrence": "weekly"
                }'

          restartPolicy: OnFailure

